### ISSUE TITLE
Push Notifications Not Working on Harmony OS

### ISSUE THREAD

**Issue by gdfGFDG52** [david-randoll/push-notification-nextjs#2]
I tested this site https://push-notification.davidrandoll.com/

The mobile phone is unsuccessful, but the desktop is successful.

Firefox 132.0 for Android
Chrome 130 Android 12.

can apply for notification permissions. After applying for permission, clicking the "Subscribe to Push Notifications" button did not respond.

The same reaction of the code I wrote myself. I registered the service on mobile, but I can't subscribe to the Push event. it work great in desktop!

![WechatIMG60](https://github.com/user-attachments/assets/cf027a6f-2649-41c7-9932-98e76fe125f3)
![WechatIMG61](https://github.com/user-attachments/assets/1ba23c21-4ef8-4f3b-880f-8d6e40c5cafd)

**Comment by david-randoll** [comment]
When you click subscribe to notifications did it by chance give u a screen like this (screenshot 1)?

![Screenshot_20241113_070527_Chrome.jpg](https://github.com/user-attachments/assets/565903b6-c92c-4ddb-a8f8-de74b3131889)

Can you click the icon on the URL and see if notification is blocked?

![Screenshot_20241113_070721_Chrome.jpg](https://github.com/user-attachments/assets/f3744b89-9800-46bc-b800-11701ad6daac)

![Screenshot_20241113_070911_Chrome.jpg](https://github.com/user-attachments/assets/ba8248b8-dc82-4234-b5a4-a800c4ef042d)

**Comment by gdfGFDG52** [comment]
The first click button has a pop-up to apply for permission toast. 
I chose to allow it. 
Then nothing changed on the page, and I clicked the button again and nothing happened.
Now there are no blocking notifications.
![IMG65](https://github.com/user-attachments/assets/fe7f2a24-9053-44e6-959e-31f449b3232b)

**Comment by david-randoll** [comment]
What model phone are you using?

Also, can you open up dev tools (F12) and go to console tab. Do you see any errors there. screenshot if you don't mind.

**Comment by gdfGFDG52** [comment]
It's a HarmonyOS system, install Android APK, you mean the system reason?

![WechatIMG69](https://github.com/user-attachments/assets/cd2f3c03-727c-4966-b632-ed107aaf4d62)

**Comment by gdfGFDG52** [comment]
![WechatIMG71](https://github.com/user-attachments/assets/7ef05e93-813b-4078-af6c-32b8a1e0d28b)

**Comment by david-randoll** [comment]
I'm going to take a look later tonight on this. The push notification might be slightly different on HarmonyOS as is on Android and IOS. 
I am wondering if it prolly similar to IOS. On IOS for the push notification to work you you need to use the "Add to Home" button. Can you try adding the app to home and then launch the app from the icon on your home screen and see if that works?

Laster tonight imma look into it and see if I can figure out a way to emulate a Harmony OS device.

**Comment by gdfGFDG52** [comment]
Last time I wrote my own subscription, I also called this method and there was a problem:
"**registration.pushManager.subscribe**" returns null on mobile phones and normal on desktops.

It could be a system issue. I haven't successfully tested it on a mobile phone so far. 
I should have asked someone else with a different system to test it.

**Comment by gdfGFDG52** [comment]
What versions of mobile systems have you tested?

**Comment by david-randoll** [comment]
> What versions of mobile systems have you tested?

I have tested on IOS 16+ and Android 11+

**Comment by david-randoll** [comment]
> ![WechatIMG71](https://private-user-images.githubusercontent.com/179072884/385798965-7ef05e93-813b-4078-af6c-32b8a1e0d28b.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NDA3MTMsIm5iZiI6MTczMTU0MDQxMywicGF0aCI6Ii8xNzkwNzI4ODQvMzg1Nzk4OTY1LTdlZjA1ZTkzLTgxM2ItNDA3OC1hZjZjLTMyYjhhMWUwZDI4Yi5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTNUMjMyNjUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWQyMWNjMTkwMjM1MGY0MzRjMzRhYTY0OWFmMTBhMDgwMDEzMDQwYWQyM2RjNzE0Y2Y4M2FiYTUyOTliODYyYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.7aLyNQ-DfjV87NTHhD4FpmWJkUYx7T-4-tkpzqK6HMI)

Can you check below link to see if maybe your browser has a settings for Enabling/Disabling push messaging? 

https://stackoverflow.com/a/69624651/11703800

**Comment by gdfGFDG52** [comment]
>  Can you check below link to see if maybe your browser has a settings for Enabling/Disabling push messaging?

What's interesting is that my system doesn't have any Google services,  can't even connect to Google servers.

In the system, only notifications, location and other permission management are set. There is no push messaging

**Comment by david-randoll** [comment]
> IOS 16.4.1 Safari browser tested is OK.
> 
> ![IMG77](https://github.com/user-attachments/assets/8bc16ff5-943d-43d9-b330-470711824aac)
> ![IMG78](https://github.com/user-attachments/assets/5460a7b0-5a01-4eab-bbe7-d604847f7031)
> 
> 
> 

awesome! It is probably just a system thing with the Harmony OS phones. I do think though push notification is supported on the Harmony OS devices but may require a specific way of implementing it.

Over the weekend, I can research it some more.

**Comment by david-randoll** [comment]
it seems if you installed microg, the push notification could possibly work. would be curious to know if this works.

https://xdaforums.com/t/fully-working-gms-notifications-and-gms-dependent-apps-tested-march-2024-harmony-os-4-3-1-3-2-emui.4664738/

**Comment by gdfGFDG52** [comment]
Kiwi Browser work!

After I installed the microG, set everything up, logged in to my Google account, reboot and reinstalled those browsers.

Kiwi Browser can be registered to get a Push subscription. The function works as expected, Amazing!!!

I also tested, and strange things happened with the browsers Firefox and Chrome. Firefox and Chrome doesn't work! Screenshot below:

# Kiwi Browser
![791731589748_ pic](https://github.com/user-attachments/assets/aa3da4c3-9d1b-4a0c-9d74-7d285de06231)
![801731589749_ pic](https://github.com/user-attachments/assets/3aa5a254-b20b-4d21-ba6f-4b24d2f1fdbe)

# Firefox 
![811731589750_ pic](https://github.com/user-attachments/assets/2d93aef6-522a-429d-be9a-2ff8aff314c7)

# Chrome
![Chrome pic](https://github.com/user-attachments/assets/dbc870c6-9e1c-4db0-a5bc-f0430573acaa)

**Comment by gdfGFDG52** [comment]
You're like a hacker! 
This question has been bothering me for half a month. There’s hardly any discussion online about my situation, so I had to experiment for a long time. 

Does this mean that all Android or Android-like push notifications go through Google servers, right?

**Comment by david-randoll** [comment]
> Kiwi Browser work!
> 
> After I installed the microG, set everything up, logged in to my Google account, reboot and reinstalled those browsers.
> 
> Kiwi Browser can be registered to get a Push subscription. The function works as expected, Amazing!!!
> 
> I also tested, and strange things happened with the browsers Firefox and Chrome. Firefox and Chrome doesn't work! Screenshot below:
> 
> # Kiwi Browser
> ![791731589748_ pic](https://private-user-images.githubusercontent.com/179072884/386206235-aa3da4c3-9d1b-4a0c-9d74-7d285de06231.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1OTQyMDcsIm5iZiI6MTczMTU5MzkwNywicGF0aCI6Ii8xNzkwNzI4ODQvMzg2MjA2MjM1LWFhM2RhNGMzLTlkMWItNGEwYy05ZDc0LTdkMjg1ZGUwNjIzMS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQxNDE4MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YzU5ODhiNTFkNDZkOTY2MzBmYWMyZDcxOWY3NTMyMmYzMjI2ZGQ1NmUwOWQwZTFhYjFlMjU1ZDFiNWM4MDZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4STJvRCCQTVrFCHcCADb2TEcAqtawrqfiL24y-1bNpY) ![801731589749_ pic](https://private-user-images.githubusercontent.com/179072884/386206250-3aa5a254-b20b-4d21-ba6f-4b24d2f1fdbe.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1OTQyMDcsIm5iZiI6MTczMTU5MzkwNywicGF0aCI6Ii8xNzkwNzI4ODQvMzg2MjA2MjUwLTNhYTVhMjU0LWIyMGItNGQyMS1iYTZmLTRiMjRkMmYxZmRiZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQxNDE4MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZjE3YjU1ZDkyYmEzZDdlMjdmMmNmZTVlN2VlZmZjNzk4ODNjYWU0ODMwMjNmZjc1Y2FiY2U5YWViMDRhMjIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wy6iU5zy41T1WRo-Tt8wmH0JmMwwAPw2NFw6smp4xjk)
> 
> # Firefox
> ![811731589750_ pic](https://private-user-images.githubusercontent.com/179072884/386206257-2d93aef6-522a-429d-be9a-2ff8aff314c7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1OTQyMDcsIm5iZiI6MTczMTU5MzkwNywicGF0aCI6Ii8xNzkwNzI4ODQvMzg2MjA2MjU3LTJkOTNhZWY2LTUyMmEtNDI5ZC1iZTlhLTJmZjhhZmYzMTRjNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQxNDE4MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOTNlMTU3N2U0MGMzNTNhODY4NGEyNmMxODhlNmVhMWY1OWIyNmQ3NTg4OTczYWYyYzc1OGIzZDdlZTNkYzg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._QkY6LR9Obfq5Cahfy78Gc6ae8H0tOLefyIe1TXxrjQ)
> 
> # Chrome
> ![Chrome pic](https://private-user-images.githubusercontent.com/179072884/386206278-dbc870c6-9e1c-4db0-a5bc-f0430573acaa.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1OTQyMDcsIm5iZiI6MTczMTU5MzkwNywicGF0aCI6Ii8xNzkwNzI4ODQvMzg2MjA2Mjc4LWRiYzg3MGM2LTllMWMtNGRiMC1hNWJjLWYwNDMwNTczYWNhYS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQxNDE4MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMTI4NzQ4ZDNjMGEyYzFmNDhhMjE3YTczMmU3ZWVjNDBkMTRmYTdjNzlkY2E3NjkxMjYxZTViZDM0NmFhZGU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.EbfSJeanCOLxANF7RptfQpL0WE7rARKOkwJvOT7eYoQ)

Awesome! I'm glad that worked.

**Comment by gdfGFDG52** [comment]
> Kiwi Browser work!
> 
> After I installed the microG, set everything up, logged in to my Google account, reboot and reinstalled those browsers.
> 
> Kiwi Browser can be registered to get a Push subscription. The function works as expected, Amazing!!!
> 
> I also tested, and strange things happened with the browsers Firefox and Chrome. Firefox and Chrome doesn't work! Screenshot below:
> 
> # Kiwi Browser
> ![791731589748_ pic](https://private-user-images.githubusercontent.com/179072884/386206235-aa3da4c3-9d1b-4a0c-9d74-7d285de06231.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1OTk2NTAsIm5iZiI6MTczMTU5OTM1MCwicGF0aCI6Ii8xNzkwNzI4ODQvMzg2MjA2MjM1LWFhM2RhNGMzLTlkMWItNGEwYy05ZDc0LTdkMjg1ZGUwNjIzMS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQxNTQ5MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYmI2MDllZTA2YjEyZGZhNjU5YmY5NWYxNTRkNmVhZGQ1ZDlkNTYzMmI0ZTZhODhlMGZhNTNkY2YyODkxYmY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QmpK4Fl2eF-5vPfJpwTSc3yH3pCeiYCBFwd0fZq5gtE) ![801731589749_ pic](https://private-user-images.githubusercontent.com/179072884/386206250-3aa5a254-b20b-4d21-ba6f-4b24d2f1fdbe.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1OTk2NTAsIm5iZiI6MTczMTU5OTM1MCwicGF0aCI6Ii8xNzkwNzI4ODQvMzg2MjA2MjUwLTNhYTVhMjU0LWIyMGItNGQyMS1iYTZmLTRiMjRkMmYxZmRiZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQxNTQ5MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MzQxOTg4ZjliM2FhYThlYjlmODkwOTJiZDg5MmE3OWViMTIzNzU3YTgzYzQ4OTM0Zjk0ZWIyMTg2YTljYmEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vab3eGSsyOb4SjfZN_aW_WvOtB7N6yO3o8OL2he5k3E)
> 
> # Firefox
> ![811731589750_ pic](https://private-user-images.githubusercontent.com/179072884/386206257-2d93aef6-522a-429d-be9a-2ff8aff314c7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1OTk2NTAsIm5iZiI6MTczMTU5OTM1MCwicGF0aCI6Ii8xNzkwNzI4ODQvMzg2MjA2MjU3LTJkOTNhZWY2LTUyMmEtNDI5ZC1iZTlhLTJmZjhhZmYzMTRjNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQxNTQ5MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMmZlNDk4NzMwMzQxNjEwNzg2ZjFhNWU2MTc2YzQ2NGI1NGEzYWY4MTE3YmZhZDkwZjVlYjAyM2ZjYjU5MzAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.GMhR3GuoOGuCdDbcZDHbRc4wqBNXnr0eUCEfUQun6bE)
> 
> # Chrome
> ![Chrome pic](https://private-user-images.githubusercontent.com/179072884/386206278-dbc870c6-9e1c-4db0-a5bc-f0430573acaa.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1OTk2NTAsIm5iZiI6MTczMTU5OTM1MCwicGF0aCI6Ii8xNzkwNzI4ODQvMzg2MjA2Mjc4LWRiYzg3MGM2LTllMWMtNGRiMC1hNWJjLWYwNDMwNTczYWNhYS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQxNTQ5MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDhmMmE2MzY4ZDY5MzFjZTNhZmFlNDlhNmZmNzU0NmY3NTc3NjBjMGUxZWQ0NmNkMzVjYzI1OTQyYWM4ZjEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.RHjqLZwFuwrB2zQwPOMLnjcMQqlJ6BPOOydBtPZ4Dv0)

I previously tested using a Chinese network, which caused this strange issue. Now, with a U.S. network proxy, everything works fine. So, my phone can now support the mainstream browser push notification features. 
_**Thank you so much!**_


![WechatIMG83](https://github.com/user-attachments/assets/0c64a34d-2749-47d4-b2b6-1dc5533a4cd8)

**Comment by david-randoll** [comment]
> > Kiwi Browser work!
> > After I installed the microG, set everything up, logged in to my Google account, reboot and reinstalled those browsers.
> > Kiwi Browser can be registered to get a Push subscription. The function works as expected, Amazing!!!
> > I also tested, and strange things happened with the browsers Firefox and Chrome. Firefox and Chrome doesn't work! Screenshot below:
> > # Kiwi Browser
> > ![791731589748_ pic](https://private-user-images.githubusercontent.com/179072884/386206235-aa3da4c3-9d1b-4a0c-9d74-7d285de06231.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1OTk2NTAsIm5iZiI6MTczMTU5OTM1MCwicGF0aCI6Ii8xNzkwNzI4ODQvMzg2MjA2MjM1LWFhM2RhNGMzLTlkMWItNGEwYy05ZDc0LTdkMjg1ZGUwNjIzMS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQxNTQ5MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYmI2MDllZTA2YjEyZGZhNjU5YmY5NWYxNTRkNmVhZGQ1ZDlkNTYzMmI0ZTZhODhlMGZhNTNkY2YyODkxYmY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QmpK4Fl2eF-5vPfJpwTSc3yH3pCeiYCBFwd0fZq5gtE) ![801731589749_ pic](https://private-user-images.githubusercontent.com/179072884/386206250-3aa5a254-b20b-4d21-ba6f-4b24d2f1fdbe.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1OTk2NTAsIm5iZiI6MTczMTU5OTM1MCwicGF0aCI6Ii8xNzkwNzI4ODQvMzg2MjA2MjUwLTNhYTVhMjU0LWIyMGItNGQyMS1iYTZmLTRiMjRkMmYxZmRiZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQxNTQ5MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MzQxOTg4ZjliM2FhYThlYjlmODkwOTJiZDg5MmE3OWViMTIzNzU3YTgzYzQ4OTM0Zjk0ZWIyMTg2YTljYmEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vab3eGSsyOb4SjfZN_aW_WvOtB7N6yO3o8OL2he5k3E)
> > # Firefox
> > ![811731589750_ pic](https://private-user-images.githubusercontent.com/179072884/386206257-2d93aef6-522a-429d-be9a-2ff8aff314c7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1OTk2NTAsIm5iZiI6MTczMTU5OTM1MCwicGF0aCI6Ii8xNzkwNzI4ODQvMzg2MjA2MjU3LTJkOTNhZWY2LTUyMmEtNDI5ZC1iZTlhLTJmZjhhZmYzMTRjNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQxNTQ5MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMmZlNDk4NzMwMzQxNjEwNzg2ZjFhNWU2MTc2YzQ2NGI1NGEzYWY4MTE3YmZhZDkwZjVlYjAyM2ZjYjU5MzAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.GMhR3GuoOGuCdDbcZDHbRc4wqBNXnr0eUCEfUQun6bE)
> > # Chrome
> > ![Chrome pic](https://private-user-images.githubusercontent.com/179072884/386206278-dbc870c6-9e1c-4db0-a5bc-f0430573acaa.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1OTk2NTAsIm5iZiI6MTczMTU5OTM1MCwicGF0aCI6Ii8xNzkwNzI4ODQvMzg2MjA2Mjc4LWRiYzg3MGM2LTllMWMtNGRiMC1hNWJjLWYwNDMwNTczYWNhYS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQxNTQ5MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDhmMmE2MzY4ZDY5MzFjZTNhZmFlNDlhNmZmNzU0NmY3NTc3NjBjMGUxZWQ0NmNkMzVjYzI1OTQyYWM4ZjEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.RHjqLZwFuwrB2zQwPOMLnjcMQqlJ6BPOOydBtPZ4Dv0)
> 
> I previously tested using a Chinese network, which caused this strange issue. Now, with a U.S. network proxy, everything works fine. So, my phone can now support the mainstream browser push notification features. _**Thank you so much!**_
> 
> ![WechatIMG83](https://private-user-images.githubusercontent.com/179072884/386268753-0c64a34d-2749-47d4-b2b6-1dc5533a4cd8.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2MDA2MjYsIm5iZiI6MTczMTYwMDMyNiwicGF0aCI6Ii8xNzkwNzI4ODQvMzg2MjY4NzUzLTBjNjRhMzRkLTI3NDktNDdkNC1iMmI2LTFkYzU1MzNhNGNkOC5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTRUMTYwNTI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzE1NGZlZjI5NDk0NjQxMmUxNWVjYTYyZWUyOTJlOWRjNWVkYWQ4Yjg5YTc0M2E2N2YzMmZlNjExOTNkNmQ2YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.gl40kJbaqk7rFqJ0PjxpvH66KfBploC13nuslp3mV-k)

Glad to hear it’s helpful! If the repo was helpful for you, feel free to leave a star—this helps GitHub suggest it to others who might benefit as well.
